### ISSUE TITLE
FYI, the signing key has been changed

### ISSUE THREAD

**Issue by nogweii** [PCextreme/ansible-role-nginx#2]
Just tried using your role today, and the SHA256SUM has changed. I get `dd4da5dc599ef9e7a7ac20a87275024b4923a917a306ab5d53fa77871220ecda` now.

Also, the role downloads the key over HTTP, but it's also available over HTTPS. May want to update the role.

And I'm curious. The nginx official site has `gpgenabled=0` in the repo configuration, so how'd you find out about the signing key?

**Comment by kevindierkx** [comment]
@evaryont Thanks for the heads up!
Regarding the key, it's actually mentioned on the nginx website: http://nginx.org/en/linux_packages.html (Bottom of the page under Signature)

I'll notify one of my colleagues to have a look at this.

**Comment by kevindierkx** [comment]
Looks like @nguyenvinhlinh already issued a fix for this for Centos, updated Ubuntu accordingly and changed the origin location of the keys to use https.
